# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

PROJECTS := library unit_tests

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

library: 
	@echo "==== Building library ($(config)) ===="
	@${MAKE} --no-print-directory -C src -f library.make

unit_tests: library
	@echo "==== Building unit_tests ($(config)) ===="
	@${MAKE} --no-print-directory -C src -f unit_tests.make

clean:
	@${MAKE} --no-print-directory -C src -f library.make clean
	@${MAKE} --no-print-directory -C src -f unit_tests.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   library"
	@echo "   unit_tests"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
